# ===============================
# esp8266-rtos-sdk-devcontainer for Podman rootless
# ===============================

FROM debian:bookworm-slim

ARG USERNAME=esp8266
ARG USER_ID=1000
ARG GROUP_ID=1000

RUN apt-get update && \
    apt-get install -y locales git wget flex bison gperf python3 python3-pip python3-virtualenv cmake ninja-build ccache libncurses-dev

RUN ln -s /usr/bin/python3 /usr/bin/python

RUN sed -i 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && locale-gen

RUN    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

RUN groupadd -g ${GROUP_ID} ${USERNAME} && \
    useradd -m -u ${USER_ID} -g ${GROUP_ID} -s /bin/bash ${USERNAME}

USER ${USERNAME}

WORKDIR /home/${USERNAME}/esp

RUN git clone -b release/v3.4 --recursive https://github.com/espressif/ESP8266_RTOS_SDK.git
WORKDIR /home/${USERNAME}/esp/ESP8266_RTOS_SDK
RUN ./install.sh

RUN echo ". /home/${USERNAME}/esp/ESP8266_RTOS_SDK/export.sh" >> /home/${USERNAME}/.profile

